#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
exec python -c "
import uvicorn
uvicorn.run(
    'config.asgi:application',
    host='0.0.0.0',
    reload=True,
    reload_includes=['*.html'],
    ws_ping_interval=None,
    ws_ping_timeout=None,
)
"
